<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-16T20:10:26 SAST" name="All Test Suite" finished-at="2024-10-16T20:13:26 SAST" duration-ms="180147">
    <groups>
    </groups>
    <test started-at="2024-10-16T20:10:26 SAST" name="First Test" finished-at="2024-10-16T20:10:55 SAST" duration-ms="28945">
      <class name="webuitests.UnitTests">
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:26 SAST" name="beforeTest" finished-at="2024-10-16T20:10:38 SAST" duration-ms="12411" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeMethod(org.testng.ITestResult, java.lang.String)[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:38 SAST" name="beforeMethod" finished-at="2024-10-16T20:10:52 SAST" duration-ms="14090" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=UnitTests.validateSiteAccessibility()[pri:0, instance:webuitests.UnitTests@2805c96b] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="beforeMethod(org.testng.ITestResult, java.lang.String)[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:38 SAST" name="beforeMethod" finished-at="2024-10-16T20:10:52 SAST" duration-ms="14090" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=UnitTests.validateLoginFailure(java.lang.String, java.lang.String)[pri:0, instance:webuitests.UnitTests@2805c96b] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validateSiteAccessibility()[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:52 SAST" name="validateSiteAccessibility" finished-at="2024-10-16T20:10:52 SAST" duration-ms="45" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at webuitests.UnitTests.validateSiteAccessibility(UnitTests.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSiteAccessibility -->
        <test-method signature="validateLoginFailure(java.lang.String, java.lang.String)[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:52 SAST" name="validateLoginFailure" data-provider="loginCredentials" finished-at="2024-10-16T20:10:54 SAST" duration-ms="1475" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tester23@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tester23]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at webuitests.UnitTests.validateLoginFailure(UnitTests.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFailure -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:53 SAST" name="afterMethod" finished-at="2024-10-16T20:10:53 SAST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:webuitests.UnitTests@2805c96b]" started-at="2024-10-16T20:10:54 SAST" name="afterMethod" finished-at="2024-10-16T20:10:55 SAST" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- webuitests.UnitTests -->
    </test> <!-- First Test -->
    <test started-at="2024-10-16T20:10:56 SAST" name="Second Test" finished-at="2024-10-16T20:13:26 SAST" duration-ms="150181">
      <class name="webuitests.UnitTests">
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:10:56 SAST" name="beforeTest" finished-at="2024-10-16T20:13:14 SAST" duration-ms="138731" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeMethod(org.testng.ITestResult, java.lang.String)[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:13:14 SAST" name="beforeMethod" finished-at="2024-10-16T20:13:22 SAST" duration-ms="8144" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=UnitTests.validateLoginFailure(java.lang.String, java.lang.String)[pri:0, instance:webuitests.UnitTests@45b9a632] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="beforeMethod(org.testng.ITestResult, java.lang.String)[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:13:14 SAST" name="beforeMethod" finished-at="2024-10-16T20:13:23 SAST" duration-ms="8621" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=UnitTests.validateSiteAccessibility()[pri:0, instance:webuitests.UnitTests@45b9a632] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validateLoginFailure(java.lang.String, java.lang.String)[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:13:22 SAST" name="validateLoginFailure" data-provider="loginCredentials" finished-at="2024-10-16T20:13:24 SAST" duration-ms="1783" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tester23@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tester23]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at webuitests.UnitTests.validateLoginFailure(UnitTests.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFailure -->
        <test-method signature="validateSiteAccessibility()[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:13:23 SAST" name="validateSiteAccessibility" finished-at="2024-10-16T20:13:23 SAST" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://parabank.parasoft.com/parabank/index.html] but found [https://parabank.parasoft.com/parabank/index.htm]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at webuitests.UnitTests.validateSiteAccessibility(UnitTests.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSiteAccessibility -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:13:23 SAST" name="afterMethod" finished-at="2024-10-16T20:13:25 SAST" duration-ms="1399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:webuitests.UnitTests@45b9a632]" started-at="2024-10-16T20:13:24 SAST" name="afterMethod" finished-at="2024-10-16T20:13:26 SAST" duration-ms="1335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- webuitests.UnitTests -->
    </test> <!-- Second Test -->
  </suite> <!-- All Test Suite -->
</testng-results>
